import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { getConfig } from "./config";

/**
 * Generates a shell wrapper script that routes command execution
 * to the devcontainer via `docker exec`.
 *
 * When OpenCode runs locally and invokes a shell command, SHELL is
 * set to this wrapper. The wrapper intercepts the command and
 * executes it inside the devcontainer instead of on the host.
 */
export function createShellWrapper(
  containerId: string,
  remoteWorkspaceFolder: string,
  envVars?: Record<string, string>
): string {
  const config = getConfig();
  const dockerPath = config.dockerPath;

  // Build environment variable flags for docker exec
  const envFlags = envVars
    ? Object.entries(envVars)
        .map(([key, value]) => `-e ${key}="${value.replace(/"/g, '\\"')}"`)
        .join(" ")
    : "";

  const script = `#!/bin/sh
# OpenCode DevContainer Shell Wrapper
# This script routes shell commands to the devcontainer.
# Generated by the opencode-for-devcontainers VS Code extension.

CONTAINER_ID="${containerId}"
WORKSPACE_DIR="${remoteWorkspaceFolder}"
DOCKER="${dockerPath}"

# If called with -c flag (standard shell -c "command" invocation),
# execute the command inside the container.
if [ "$1" = "-c" ]; then
  shift
  exec "$DOCKER" exec -w "$WORKSPACE_DIR" ${envFlags} "$CONTAINER_ID" sh -c "$@"
fi

# If called with arguments but no -c flag, pass them as a command.
if [ $# -gt 0 ]; then
  exec "$DOCKER" exec -w "$WORKSPACE_DIR" ${envFlags} "$CONTAINER_ID" sh -c "$*"
fi

# If called with no arguments, open an interactive shell in the container.
exec "$DOCKER" exec -it -w "$WORKSPACE_DIR" ${envFlags} "$CONTAINER_ID" sh
`;

  return script;
}

/**
 * Write the shell wrapper to a temporary file and return its path.
 */
export function writeShellWrapper(
  containerId: string,
  remoteWorkspaceFolder: string,
  envVars?: Record<string, string>
): string {
  const script = createShellWrapper(containerId, remoteWorkspaceFolder, envVars);
  const tmpDir = path.join(os.tmpdir(), "opencode-devcontainer");

  if (!fs.existsSync(tmpDir)) {
    fs.mkdirSync(tmpDir, { recursive: true });
  }

  const wrapperPath = path.join(tmpDir, `shell-wrapper-${containerId.substring(0, 12)}.sh`);
  fs.writeFileSync(wrapperPath, script, { mode: 0o755 });

  return wrapperPath;
}

/**
 * Clean up the shell wrapper file.
 */
export function removeShellWrapper(wrapperPath: string): void {
  try {
    if (fs.existsSync(wrapperPath)) {
      fs.unlinkSync(wrapperPath);
    }
  } catch {
    // Best-effort cleanup
  }
}
